# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13a12590b0a7b71113b1589defea5d3ad4c5f44b0ea78b823d547fd115bff3150624fe3178e818dcd8f21d5f89b81f1f575f7b4f9e744d112accf83debfd9da7

test:
  secret_key_base: 69bcfa6a3b6274a0d3a9f8ab98651cf8fc0068b4e0c7a946f5e95399165d6c4494d63602856e30a8c7acfcea4fa56f7e8614bca754c2c19826c3fadecfe4446e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
